In [142]:
import pandas as pd

In [143]:
pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [144]:
df = pd.DataFrame({
    "Name": ["John", "Alice", "Kabali", "Sameer", "Ramesh"],
    "CRN": [223343, 223309, 223359, 223394, 223354],
    "Age" : [20, 21, 19, 19, 20],
    "Attendence": [10, 11, 12, 11, None]},
index = [1, 2, 3, 4, 5])
df

     Name     CRN  Age  Attendence
1    John  223343   20        10.0
2   Alice  223309   21        11.0
3  Kabali  223359   19        12.0
4  Sameer  223394   19        11.0
5  Ramesh  223354   20         NaN

In [145]:
df.head(2)

    Name     CRN  Age  Attendence
1   John  223343   20        10.0
2  Alice  223309   21        11.0

In [146]:
df.iloc[0:2, 0:2]

    Name     CRN
1   John  223343
2  Alice  223309

In [147]:
df.loc[0:2]

    Name     CRN  Age  Attendence
1   John  223343   20        10.0
2  Alice  223309   21        11.0

In [148]:
df.describe()

                 CRN       Age  Attendence
count       5.000000   5.00000    4.000000
mean   223351.800000  19.80000   11.000000
std        30.605555   0.83666    0.816497
min    223309.000000  19.00000   10.000000
25%    223343.000000  19.00000   10.750000
50%    223354.000000  20.00000   11.000000
75%    223359.000000  20.00000   11.250000
max    223394.000000  21.00000   12.000000

In [149]:
df.info()

<class 'pandas.DataFrame'>
Index: 5 entries, 1 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      str
 1   CRN         5 non-null      int64
 2   Age         5 non-null      int64
 3   Attendence  4 non-null      float64
dtypes: float64(1), int64(2), str(1)
memory usage: 372.0 bytes

In [150]:
df.shape

(5, 4)

In [151]:
df.groupby('Age').count()

     Name  CRN  Attendence
Age
19      2    2           2
20      2    2           1
21      1    1           1

In [152]:
df.dropna()

     Name     CRN  Age  Attendence
1    John  223343   20        10.0
2   Alice  223309   21        11.0
3  Kabali  223359   19        12.0
4  Sameer  223394   19        11.0

In [156]:
df = df.fillna(10)

In [166]:
# df.filter(like='column_name')
df.filter(like='Name')

     Name
1    John
2   Alice
3  Kabali
4  Sameer
5  Ramesh

In [155]:
df.tail(2)

     Name     CRN  Age  Attendence
4  Sameer  223394   19        11.0
5  Ramesh  223354   20        10.0